dnase/bamintersect/submit_bamintersect.sh
When bamintersect is doing the initial bam1 sort of all the mm10/hg38/rn6 reads (in sort_bamintersect.sh), it is throwing out all the proper pairs from the bam1 file.
So when the cegsvectors insertion is almost identical to the deletion, this means almost all reads with unmapped mates in the bam2 file will have no corresponding mate in the insertion chromosome in the list of surviving bam1 reads.
This commit stops the above behavior.
=> Change bam exclude flags from 3078 to 3076

dnase/bamintersect/counts_table.sh
At line 155 in the counts_table.sh pipeline, there are no headers in the output from annotateNearestGeneName. This headerless output is being passed as input to mlr.
In the particular case of BS04412A, for each +/- strand combination there are only zero or one lines coming out from annotateNearestGeneName. So that one line is
interpreted by mlr as a header, and no output at all is passed from mlr to awk. This eventually results in an empty counts.txt file.
This fix replaces mlr with a call to standard sort.
=> Replace mlr with sort to fix counts_table.sh

transposon/analyzeBCcounts.sh
added the code to generate a saturation curve of the BC+cellBC combination on 10XRNA libraries to the analyzeBCcounts.sh script.
The code as of right now is largely based on the previous saturation curve calculation.
=> Added BC+cellBC saturation curve computation

transposon/genotypeClones.py
add color scheme support for coloring BCs according to their T0219toT0222 transfections. After adding the code above, you will be able to color the clones using `/vol/mauranolab/ribeia01/transposon_10x/T0219toT0221/bc_transfection-occurrence.txt.gz`
=> Add support for coloring T0219toT0222

transposon/genotypeClones.py
Hi Matt,
on my last PR I just notice a typo of `parset` instead of `parser` and I am sending this to fix it. Also, the `analyzeBCcounts.sh` is calling the script defaulting `--maxConflictRate` to 0.0 which corresponds to the harsh cutoff, do you want to use it or 0.10 instead?
=> fix genotypeClones.py typo

transposon/analyzeBCcounts.sh, transposon/genotypeClones.py
Here, I am proposing a new interface to add the post clean-up of conflicting clones to `genotypeClones.py`.
- Replaced the previous interface and added three parameters:
- `transfectionKey`, to determinate which attribute identifies BCs transfection
- `maxConflictRate [rate]`, to determinate a maximum conflict rate for which we will try to recover conflicting cells
- `removeConflictingCells`, a flag to determinate if after all should we remove conflict cells
- It uses two new functions for this clean-up `pruneConflictingEdges` and `pruneConflictingCells`.
- Removed the previous interface usage from `analyzeBCscounts.sh`
=> New post genotypeClones.py clean-up interface proposal

transposon/genotypeClones.py
On my test-run, I noticed a bug on `pruneConflictingCells`.
Here is a fix that solves this issue that causes an exception on trying to remove edges linked to removed cells.
=> fix genotypeClones update bugs

transposon/genotypeClones.py
I've noticed that my code was getting stuck when running `remove_edges` which was solved by passing a `set` instead of `list`. Here I've implemented this optimization at the function level to speed-up genotypeClones execution.
=> genotypeClones speedup

transposon/genotypeClones.py
Using the same strategy as before, we can improve slightly `breakUpWeaklyConnectedCommunities` performance by converting `nodesToPrune` to a `set` instead of list.
The improvement here is less noticeable, but it does improve performance. My last runs have lasted less than a day even with relaxed cutoff filters.
=> breakUpWeaklyConnectedCommunities speed-up

dnase/bamintersect/HA_table.sh, dnase/bamintersect/merge_bamintersect.sh, dnase/bamintersect/submit_bamintersect.sh, dnase/submit.sh
The optional normbam parameter is passed to merge_bamintersect.sh, and is used there instead of bam1 as the basis for counting reads for normalization.
Also fixed a typo in HA_table.sh   --readNames ==> --include_readnames
This change was overlooked in the "stop making .counts.informative.bed files as their utility is reduced" commit.
fixes #228
=> Permit passing separate bam file to count reads for normalization

transposon/genotypeClones.py
Hi,
upon reviewing the `genotypeClones.py` code results I noticed two bugs that I commit solutions here:
- `computeKeyRate` was using the BCs total weight instead of the edge weight to estimate the transfections rate. I included a `source`  parameter to determine the edges and correctly compute the rates.
- `remove_edges` was excluding edges twice or not decreasing the node's total weight of some edges were being excluded making the total weight inconsistent with the sum of the weight of the edges. As `G.edges` emit edges on arbitrary order (either (BC, cellBC) or (cellBC, BC)) sometimes they were not recognized as included to `edgesToRemove`. To fix this I've added the reverted order to `edgesToRemove` which accounts for either cases and guarantees consistency.
=> Genotype clones fixes

transposon/genotypeClones.py
Here I propose an update to conflict resolution by removing conflicting BCs (in this case BCs linked to cells from 2+ transfections) when `genotypeClones.py` is called with `--pruneConflictingBCs`.
It also updated `pruneConflictingCells` to `pruneConflictingNodes` as a generic version that can resolve either Cell or BC pruning.
=> Add remove conflicting BCs

transposon/genotypeClones.py
This is a fix for two bugs raised when running `pruneConflictingNodes` from `genotypeClones.py`. The following errors were raised during test-run
(1) 
```
Traceback (most recent call last):
File "/vol/mauranolab/mapped/src/transposon/genotypeClones.py", line 565, in <module>
pruneConflictingNodes(G, args.transfectionKey, type = "cell")
File "/vol/mauranolab/mapped/src/transposon/genotypeClones.py", line 232, in pruneConflictingNodes
nodes_to_remove.add(bc)
NameError: name 'bc' is not defined
```
(2)
```
Traceback (most recent call last):
File "/vol/mauranolab/ribeia01/transposon_10x/mapping/transposon/genotypeClones.py", line 567, in <module>
pruneConflictingNodes(G, args.transfectionKey, type = "BC")
File "/vol/mauranolab/ribeia01/transposon_10x/mapping/transposon/genotypeClones.py", …
```
=> fixPruneConflictNodesBug

transposon/analyzeIntegrations.sh, transposon/extractBCcounts.sh, transposon/extractBarcode.py, transposon/mapIntegrations.sh, transposon/removeOverrepresentedBCs.py, transposon/submit.sh, transposon/submitMerge.sh
Here I propose some changes to iPCR mapping pipeline to enable it to deal with iPCR with no BC sequence. A priori, I am skipping extractBCs.sh for such cases.
Besides that I've made mapIntegrations.sh trimming more adaptable to the primer sequence template given as parameter.
=> Add no bc support to ipcr mapping

dnase/trackhub/MakeTrackhub.py
This enables the itemRgb parameter.
I also changed maxItems to 2500 from 250.  When the number of items displayed from the bb file exceeds this value, the coloring is turned off.
=> Adjust MakeTrackhub.py to read 9 columns from bb files.

transposon/AdjacencyDeDup.py
I was investigating the issue freezing Raquel Ordonez processing and besides some other changes with minor speed improvement, the main issue I detect is the inclusion check on `get_connected_components_adjacency` which uses a list instead of a set that is much faster. On my tests, the execution that ran overnight was able to complete in a couple of minutes.
=> SpeedUp AdjacencyDeDup.py

transposon/extractBarcode.py
Modified `extractBarcodes.py` to add noBC runs support.
I've modified the script to skip some checks when no barcode is found in the reference sequence.
=> add check if noBC length and skip check

transposon/analyzeIntegrations.sh, transposon/mapIntegrations.sh, transposon/submitMerge.sh
Included 3 configurable parameters (`minLengthForPEmapping`,  `cutadaptR1args`, `cutadaptR2args`) to adapt mapIntegrations when necessary.
=> Add configurable parameters to mapIntegrations.sh

transposon/analyzeIntegrations.sh
This PR fixes the `.SingleIns.txt` file check that made the pipeline skip the removal of multIns reporters.
=> fix analyzeIntegrations.sh bug that prevent selection of single-site

transposon/genotypeClones.py
This PR aims to extend `genotypeClones.py` output to include the BC and Clone transfections assigned when available. It changes the `.clones.txt` file to a table with the following columns:
- BCs
- cellBCs
- clone
- **transfection** (new column included here)
- count
- nedges
- nBCs
- ncells
and changes `.clones.counts.filtered.txt` file to a table with the following columns:
- BC
- **BCTransfection**  (new column included here)
- clone
- **transfection**  (new column included here)
- count
- nCells
=> Output clone transfection

transposon/genotypeClones.py
This PR includes:
- a consistency fix to make the results of `genotypeClones.py` consistent between multiple runs.
- When executed multiple times, the code produced slightly different results due to bridges ordering, which was random between bridges of the same `weight`. To ensure consistent behaviour, I ordered edge vertices and when sorting bridges, also sorted them by the vertices.
- two small code optimizations to improve processing time.
- Added a quick skip of border bridges, linking a component to a node without any other connection.
- Replace `subG.copy`, by `nx.restricted_view(subG, [], [edge])` which produce a view of the graph hiding the bridge edge. This avoids the heavy step of cloning `subG` and significantly reduced processing time
=> genotypeClones improvement

dnase/trackhub/MakeTrackhub.py
Fix intended to make `MakeTrackhub.py` compatible with the updated version of trackhub (`v0.2.4-mauranolab`). For such purpose, it was necessary to:
- replace all instances of `parentonoff` by `parent`
=> MakeTrackhub.py compatible with updated trackhub

dnase/trackhub/samplesforTrackhub.R
Fixes: #276
Profiling showed that the data `data.frame` was being duplicated after any updates.
Looking into this, I found that this is an issue when updating `data.frame` values.
Using `data.table` allows for values to be updated in place without the duplication cost.
But this required preallocating all the entries in the data table when it is created.
Another area I still need to investigate is improving the use of `grep` in the code.
There are two areas worth focusing on:
1. The same grep statement is being used in an if statement and then again in an assignment
a. This could be improved by storing the result in a variable and using that instead
2. Some grep statements could be replaced with %in% statements, which might be faster
It will be worth looking into `data.table` `%like%` …
=> make samplesforTrackhub more performant

dnase/trackhub/MakeTrackhub.py, dnase/trackhub/makeChroms_per_cegsvectorHtml.R, dnase/trackhub/makeDescHtml.R
Changes:
+ Set a fixed class name instead of the default random name generated by the library
+ Sort the assays set to ensure the traversal order is the same between runs
Testing:
I ran the update_tracks.sh script twice and compared the output using `diff -q -r`. The only difference between the outputs is the `Hub was constructed at:` time. 
resolves #283
=> fix: track description reproducibility
